/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-03T10:40:46.900855+00:00
/// Collection: arcticons
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/arcticons/>
///
/// ```yaml
/// name: Arcticons
/// author:
///   name: Donnnno
///   url: https://github.com/Arcticons-Team/Arcticons
/// license:
///   title: CC BY-SA 4.0
///   spdx: CC-BY-SA-4.0
///   url: https://creativecommons.org/licenses/by-sa/4.0/
/// total: 14714
/// category: Logos
/// palette: false
/// height: 48
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const IcloudDrive: IconData = IconData {
    name: "arcticons:icloud-drive",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="M10.958 20.261a.59.59 0 0 1-.525.529C7.08 21.15 4.5 24.452 4.5 28.47c0 4.26 2.954 7.713 6.598 7.713H36.25c4.004 0 7.249-3.65 7.249-8.15c0-4.315-2.98-7.846-6.752-8.133a.63.63 0 0 1-.578-.506c-.843-4.328-4.73-7.58-9.325-7.58c-2.987 0-5.647 1.353-7.375 3.504c-.169.21-.452.307-.701.202a5.45 5.45 0 0 0-2.153-.414c-2.969 0-5.405 2.266-5.659 5.154"/>"#,
    view_box: "0 0 48 48",
    width: "48",
    height: "48",
};
