/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-12T06:29:17.697224+00:00
/// Collection: basil
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/basil/>
///
/// ```yaml
/// name: Basil
/// author:
///   name: Craftwork
///   url: https://www.figma.com/community/file/931906394678748246
/// license:
///   title: CC BY 4.0
///   spdx: CC-BY-4.0
///   url: https://creativecommons.org/licenses/by/4.0/
/// total: 493
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const ExpandOutline: IconData = IconData {
    name: "basil:expand-outline",
    body: r#"<path fill="currentColor" fill-rule="evenodd" d="M13.664 6.343c0 .414.336.75.75.75h2.493v2.493a.75.75 0 0 0 1.5 0V6.343a.75.75 0 0 0-.75-.75h-3.243a.75.75 0 0 0-.75.75m3.993 7.321a.75.75 0 0 0-.75.75v2.493h-2.493a.75.75 0 1 0 0 1.5h3.243a.75.75 0 0 0 .75-.75v-3.243a.75.75 0 0 0-.75-.75m-11.314 0a.75.75 0 0 1 .75.75v2.493h2.493a.75.75 0 0 1 0 1.5H6.343a.75.75 0 0 1-.75-.75v-3.243a.75.75 0 0 1 .75-.75m3.993-7.321a.75.75 0 0 1-.75.75H7.093v2.493a.75.75 0 1 1-1.5 0V6.343a.75.75 0 0 1 .75-.75h3.243a.75.75 0 0 1 .75.75" clip-rule="evenodd"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
