/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-03T10:28:25.398491+00:00
/// Collection: bxs
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/bxs/>
///
/// ```yaml
/// name: BoxIcons v2 Solid
/// author:
///   name: Boxicons
///   url: https://github.com/box-icons/boxicons
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/box-icons/boxicons/blob/main/LICENSE
/// total: 665
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Videos: IconData = IconData {
    name: "bxs:videos",
    body: r#"<path fill="currentColor" d="M4 8H2v12a2 2 0 0 0 2 2h12v-2H4z"/><path fill="currentColor" d="M20 2H8a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2m-9 12V6l7 4z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
