/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-17T14:38:46.506173+00:00
/// Collection: cuida
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/cuida/>
///
/// ```yaml
/// name: Cuida Icons
/// author:
///   name: Sysvale
///   url: https://github.com/Sysvale/cuida-icons
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/Sysvale/cuida-icons/blob/main/LICENSE
/// total: 182
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const CopyOutline: IconData = IconData {
    name: "cuida:copy-outline",
    body: r#"<g class="copy-outline"><g fill="currentColor" fill-rule="evenodd" class="Vector" clip-rule="evenodd"><path d="M2 11.667a3.4 3.4 0 0 1 3.4-3.4h2.205v2H5.4a1.4 1.4 0 0 0-1.4 1.4v7.2a1.4 1.4 0 0 0 1.4 1.4h7.2a1.4 1.4 0 0 0 1.4-1.4v-1.8h2v1.8a3.4 3.4 0 0 1-3.4 3.4H5.4a3.4 3.4 0 0 1-3.4-3.4z"/><path d="M10 3h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4h-8a4 4 0 0 1-4-4V7a4 4 0 0 1 4-4m0 2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2z"/></g></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
