/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-25T06:29:33.654898+00:00
/// Collection: eos-icons
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/eos-icons/>
///
/// ```yaml
/// name: EOS Icons
/// author:
///   name: SUSE UX/UI team
///   url: https://gitlab.com/SUSE-UIUX/eos-icons
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://gitlab.com/SUSE-UIUX/eos-icons/-/blob/master/LICENSE
/// total: 253
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const ModifiedDateOutlined: IconData = IconData {
    name: "eos-icons:modified-date-outlined",
    body: r#"<path fill="currentColor" d="m13.372 11.013l.614.614l-6.04 6.04h-.613v-.614zM15.771 7a.67.67 0 0 0-.467.193l-1.22 1.22l2.5 2.5l1.22-1.22a.664.664 0 0 0 0-.94l-1.56-1.56A.66.66 0 0 0 15.772 7m-2.4 2.127L6 16.5V19h2.5l7.372-7.373Z"/><path fill="currentColor" d="M19 1h-2v2H7V1H5v2H4a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2h-1zM4 21V5h16v16Z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const SubscriptionsCreatedOutlined: IconData = IconData {
    name: "eos-icons:subscriptions-created-outlined",
    body: r#"<path fill="currentColor" d="M20 8H4V6h16Zm-2-6H6v2h12Zm-7.688 19.1l-3.3-3.3l1.4-1.4l1.9 1.9l5.3-5.3l1.4 1.4Z"/><path fill="currentColor" d="M22 10H2a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h20a2 2 0 0 0 2-2V12a2 2 0 0 0-2-2m0 12H2V12h20Z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
