/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-26T14:33:03.346677+00:00
/// Collection: fa6-regular
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/fa6-regular/>
///
/// ```yaml
/// name: Font Awesome 6 Regular
/// author:
///   name: Dave Gandy
///   url: https://github.com/FortAwesome/Font-Awesome
/// license:
///   title: CC BY 4.0
///   spdx: CC-BY-4.0
///   url: https://creativecommons.org/licenses/by/4.0/
/// total: 163
/// category: Archive / Unmaintained
/// palette: false
/// height: 32
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Paste: IconData = IconData {
    name: "fa6-regular:paste",
    body: r#"<path fill="currentColor" d="M104.6 48H64C28.7 48 0 76.7 0 112v272c0 35.3 28.7 64 64 64h96v-48H64c-8.8 0-16-7.2-16-16V112c0-8.8 7.2-16 16-16h16c0 17.7 14.3 32 32 32h72.4c17.6-19.6 43.2-32 71.6-32h62c-7.1-27.6-32.2-48-62-48h-40.6C211.6 20.9 188.2 0 160 0s-51.6 20.9-55.4 48m39.4 8a16 16 0 1 1 32 0a16 16 0 1 1-32 0m304 408H256c-8.8 0-16-7.2-16-16V192c0-8.8 7.2-16 16-16h140.1l67.9 67.9V448c0 8.8-7.2 16-16 16m-192 48h192c35.3 0 64-28.7 64-64V243.9c0-12.7-5.1-24.9-14.1-33.9L430 142.1c-9-9-21.2-14.1-33.9-14.1H256c-35.3 0-64 28.7-64 64v256c0 35.3 28.7 64 64 64"/>"#,
    view_box: "0 0 512 512",
    width: "512",
    height: "512",
};
