/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-17T14:35:45.412371+00:00
/// Collection: gg
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/gg/>
///
/// ```yaml
/// name: css.gg
/// author:
///   name: Astrit
///   url: https://github.com/astrit/css.gg
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/astrit/css.gg/blob/master/LICENSE
/// total: 704
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Rename: IconData = IconData {
    name: "gg:rename",
    body: r#"<g fill="currentColor"><path fill-rule="evenodd" d="M10 4H8v2H5a3 3 0 0 0-3 3v6a3 3 0 0 0 3 3h3v2h2zM8 8v8H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1z" clip-rule="evenodd"/><path d="M19 16h-7v2h7a3 3 0 0 0 3-3V9a3 3 0 0 0-3-3h-7v2h7a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
