/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-25T06:30:15.597916+00:00
/// Collection: icon-park-outline
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/icon-park-outline/>
///
/// ```yaml
/// name: IconPark Outline
/// author:
///   name: ByteDance
///   url: https://github.com/bytedance/IconPark
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/bytedance/IconPark/blob/master/LICENSE
/// total: 2658
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Permissions: IconData = IconData {
    name: "icon-park-outline:permissions",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="4"><path stroke-linejoin="round" d="M20 10H6a2 2 0 0 0-2 2v26a2 2 0 0 0 2 2h36a2 2 0 0 0 2-2v-2.5"/><path d="M10 23h8m-8 8h24"/><circle cx="34" cy="16" r="6" stroke-linejoin="round"/><path stroke-linejoin="round" d="M44 28.419C42.047 24.602 38 22 34 22s-5.993 1.133-8.05 3"/></g>"#,
    view_box: "0 0 48 48",
    width: "48",
    height: "48",
};
