/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-26T14:28:12.434797+00:00
/// Collection: iconoir
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/iconoir/>
///
/// ```yaml
/// name: Iconoir
/// author:
///   name: Luca Burgio
///   url: https://github.com/iconoir-icons/iconoir
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/iconoir-icons/iconoir/blob/main/LICENSE
/// total: 1671
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Finder: IconData = IconData {
    name: "iconoir:finder",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"><path d="M3 15V9a6 6 0 0 1 6-6h6a6 6 0 0 1 6 6v6a6 6 0 0 1-6 6H9a6 6 0 0 1-6-6"/><path d="M15 3s-4.5 0-4.5 9H13c0 9 2 9 2 9"/><path d="M16.5 14.5s-1.5 2-4.5 2s-4.5-2-4.5-2M7 9v2m10-2v2"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
