/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-17T14:39:31.704251+00:00
/// Collection: ion
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/ion/>
///
/// ```yaml
/// name: IonIcons
/// author:
///   name: Ben Sperry
///   url: https://github.com/ionic-team/ionicons
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/ionic-team/ionicons/blob/main/LICENSE
/// total: 1357
/// category: UI 16px / 32px
/// palette: false
/// height: 32
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const DuplicateOutline: IconData = IconData {
    name: "ion:duplicate-outline",
    body: r#"<rect width="336" height="336" x="128" y="128" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32" rx="57" ry="57"/><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="m383.5 128l.5-24a56.16 56.16 0 0 0-56-56H112a64.19 64.19 0 0 0-64 64v216a56.16 56.16 0 0 0 56 56h24m168-168v160m80-80H216"/>"#,
    view_box: "0 0 512 512",
    width: "512",
    height: "512",
};
