/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-25T07:20:21.583030+00:00
/// Collection: ix
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/ix/>
///
/// ```yaml
/// name: Siemens Industrial Experience Icons
/// author:
///   name: Siemens AG
///   url: https://github.com/siemens/ix-icons
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/siemens/ix-icons/blob/main/LICENSE.md
/// total: 1415
/// category: UI Other / Mixed Grid
/// palette: false
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Tree: IconData = IconData {
    name: "ix:tree",
    body: r#"<path fill="currentColor" fill-rule="evenodd" d="M85.333 64h128v64h-128zM192 170.667h128v64H192zm0 106.666h128v64H192zM298.666 384h128v64h-128zM160 149.333v32h10.666v32H128v-64zm106.666 213.334v32h10.667v32h-42.667v-64zM160 234.667V288h10.666v32H128v-85.333z"/>"#,
    view_box: "0 0 512 512",
    width: "512",
    height: "512",
};
