/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-03T10:32:40.494735+00:00
/// Collection: line-md
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/line-md/>
///
/// ```yaml
/// name: Material Line Icons
/// author:
///   name: Vjacheslav Trushkin
///   url: https://github.com/cyberalien/line-md
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/cyberalien/line-md/blob/main/license.txt
/// total: 1218
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const File: IconData = IconData {
    name: "line-md:file",
    body: r#"<g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path fill="none" stroke-dasharray="62" d="M13.5 3l5.5 5.5v11.5c0 0.55 -0.45 1 -1 1h-12c-0.55 0 -1 -0.45 -1 -1v-16c0 -0.55 0.45 -1 1 -1Z"><animate fill="freeze" attributeName="stroke-dashoffset" dur="0.6s" values="62;0"/></path><path fill="currentColor" d="M14 3.5l0 4.5l4.5 0Z" opacity="0"><set fill="freeze" attributeName="opacity" begin="0.6s" to="1"/><animate fill="freeze" attributeName="d" begin="0.6s" dur="0.2s" values="M14 3.5l2.25 2.25l2.25 2.25Z;M14 3.5l0 4.5l4.5 0Z"/></path></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Folder: IconData = IconData {
    name: "line-md:folder",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path stroke-dasharray="62" d="M12 7h8c0.55 0 1 0.45 1 1v10c0 0.55 -0.45 1 -1 1h-16c-0.55 0 -1 -0.45 -1 -1v-11Z"><animate fill="freeze" attributeName="stroke-dashoffset" dur="0.6s" values="62;0"/></path><path d="M12 7h-9v-1c0 -0.55 0.45 -1 1 -1h6Z" opacity="0"><set fill="freeze" attributeName="opacity" begin="0.6s" to="1"/><animate fill="freeze" attributeName="d" begin="0.6s" dur="0.2s" values="M12 7h-9v0c0 0 0.45 0 1 0h6Z;M12 7h-9v-1c0 -0.55 0.45 -1 1 -1h6Z"/></path></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Trash: IconData = IconData {
    name: "line-md:trash",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path stroke-dasharray="24" d="M12 20h5c0.5 0 1 -0.5 1 -1v-14M12 20h-5c-0.5 0 -1 -0.5 -1 -1v-14"><animate fill="freeze" attributeName="stroke-dashoffset" dur="0.5s" values="24;0"/></path><path stroke-dasharray="18" stroke-dashoffset="18" d="M4 5h16"><animate fill="freeze" attributeName="stroke-dashoffset" begin="0.5s" dur="0.3s" to="0"/></path><path stroke-dasharray="10" stroke-dashoffset="10" d="M10 4h4M10 9v7M14 9v7"><animate fill="freeze" attributeName="stroke-dashoffset" begin="0.8s" dur="0.2s" to="0"/></path></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
