/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-25T07:18:25.081390+00:00
/// Collection: lucide
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/lucide/>
///
/// ```yaml
/// name: Lucide
/// author:
///   name: Lucide Contributors
///   url: https://github.com/lucide-icons/lucide
/// license:
///   title: ISC
///   spdx: ISC
///   url: https://github.com/lucide-icons/lucide/blob/main/LICENSE
/// total: 1743
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const FolderSync: IconData = IconData {
    name: "lucide:folder-sync",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M9 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v.5"/><path d="M12 10v4h4"/><path d="m12 14l1.535-1.605a5 5 0 0 1 8 1.5M22 22v-4h-4"/><path d="m22 18l-1.535 1.605a5 5 0 0 1-8-1.5"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
