/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-18T02:19:52.288974+00:00
/// Collection: material-symbols-light
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/material-symbols-light/>
///
/// ```yaml
/// name: Material Symbols Light
/// author:
///   name: Google
///   url: https://github.com/google/material-design-icons
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/google/material-design-icons/blob/master/LICENSE
/// total: 15507
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const CreateNewFolderOutline: IconData = IconData {
    name: "material-symbols-light:create-new-folder-outline",
    body: r#"<path fill="currentColor" d="M14.5 15.5h1v-2h2v-1h-2v-2h-1v2h-2v1h2zM4.616 19q-.691 0-1.153-.462T3 17.384V6.616q0-.691.463-1.153T4.615 5h4.981l2 2h7.789q.69 0 1.153.463T21 8.616v8.769q0 .69-.462 1.153T19.385 19zm0-1h14.769q.269 0 .442-.173t.173-.442v-8.77q0-.269-.173-.442T19.385 8h-8.19l-2-2h-4.58q-.269 0-.442.173T4 6.616v10.769q0 .269.173.442t.443.173M4 18V6z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const FolderZipOutlineRounded: IconData = IconData {
    name: "material-symbols-light:folder-zip-outline-rounded",
    body: r#"<path fill="currentColor" d="M16 12v-2h2v2zm0 2h-2v-2h2zm0 2v-2h2v2zm-4.806-8l-2-2H4.615q-.269 0-.442.173T4 6.616v10.769q0 .269.173.442t.443.173H14v-2h2v2h3.385q.269 0 .442-.173t.173-.442v-8.77q0-.269-.173-.442T19.385 8H16v2h-2V8zM4.615 19q-.69 0-1.153-.462T3 17.384V6.616q0-.691.463-1.153T4.615 5h4.31q.323 0 .628.13q.305.132.522.349L11.596 7h7.789q.69 0 1.153.463T21 8.616v8.769q0 .69-.462 1.153T19.385 19zM4 18V6z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
