/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-03T10:38:06.337034+00:00
/// Collection: material-symbols
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/material-symbols/>
///
/// ```yaml
/// name: Material Symbols
/// author:
///   name: Google
///   url: https://github.com/google/material-design-icons
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/google/material-design-icons/blob/master/LICENSE
/// total: 15450
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const DownloadRounded: IconData = IconData {
    name: "material-symbols:download-rounded",
    body: r#"<path fill="currentColor" d="M11.625 15.513q-.175-.063-.325-.213l-3.6-3.6q-.3-.3-.288-.7t.288-.7q.3-.3.713-.312t.712.287L11 12.15V5q0-.425.288-.712T12 4t.713.288T13 5v7.15l1.875-1.875q.3-.3.713-.288t.712.313q.275.3.288.7t-.288.7l-3.6 3.6q-.15.15-.325.213t-.375.062t-.375-.062M6 20q-.825 0-1.412-.587T4 18v-2q0-.425.288-.712T5 15t.713.288T6 16v2h12v-2q0-.425.288-.712T19 15t.713.288T20 16v2q0 .825-.587 1.413T18 20z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const HardDriveOutline: IconData = IconData {
    name: "material-symbols:hard-drive-outline",
    body: r#"<path fill="currentColor" d="M4 17h16v-6H4zm14.063-1.937q.437-.438.437-1.063t-.437-1.062T17 12.5t-1.062.438T15.5 14t.438 1.063T17 15.5t1.063-.437M22 9h-2.825l-2-2H6.825l-2 2H2l3.425-3.425q.275-.275.638-.425T6.825 5h10.35q.4 0 .763.15t.637.425zM4 19q-.825 0-1.412-.587T2 17V9h20v8q0 .825-.587 1.413T20 19z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const HomeOutlineRounded: IconData = IconData {
    name: "material-symbols:home-outline-rounded",
    body: r#"<path fill="currentColor" d="M6 19h3v-5q0-.425.288-.712T10 13h4q.425 0 .713.288T15 14v5h3v-9l-6-4.5L6 10zm-2 0v-9q0-.475.213-.9t.587-.7l6-4.5q.525-.4 1.2-.4t1.2.4l6 4.5q.375.275.588.7T20 10v9q0 .825-.588 1.413T18 21h-4q-.425 0-.712-.288T13 20v-5h-2v5q0 .425-.288.713T10 21H6q-.825 0-1.412-.587T4 19m8-6.75"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
