/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-03T10:26:22.893367+00:00
/// Collection: mdi
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/mdi/>
///
/// ```yaml
/// name: Material Design Icons
/// author:
///   name: Pictogrammers
///   url: https://github.com/Templarian/MaterialDesign
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/Templarian/MaterialDesign/blob/master/LICENSE
/// total: 7447
/// category: Material
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Music: IconData = IconData {
    name: "mdi:music",
    body: r#"<path fill="currentColor" d="M21 3v12.5a3.5 3.5 0 0 1-3.5 3.5a3.5 3.5 0 0 1-3.5-3.5a3.5 3.5 0 0 1 3.5-3.5c.54 0 1.05.12 1.5.34V6.47L9 8.6v8.9A3.5 3.5 0 0 1 5.5 21A3.5 3.5 0 0 1 2 17.5A3.5 3.5 0 0 1 5.5 14c.54 0 1.05.12 1.5.34V6z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
