// Auto-generated by dioxus-iconify - DO NOT EDIT
use dioxus::prelude::*;

#[derive(Clone, Copy, PartialEq)]
pub struct IconData {
    pub name: &'static str,
    pub body: &'static str,
    pub view_box: &'static str,
    pub width: &'static str,
    pub height: &'static str,
}

#[component]
pub fn Icon(
    data: IconData,
    /// Optional size to set both width and height
    #[props(default, into)]
    size: String,
    /// Additional attributes to extend the svg element
    #[props(extends = SvgAttributes)]
    attributes: Vec<Attribute>,
) -> Element {
    let (width, height) = if size.is_empty() {
        (data.width, data.height)
    } else {
        (size.as_str(), size.as_str())
    };

    rsx! {
        svg {
            view_box: "{data.view_box}",
            width: "{width}",
            height: "{height}",
            dangerous_inner_html: "{data.body}",
            ..attributes,
        }
    }
}

pub mod basil;
pub mod boxicons;
pub mod bxs;
pub mod clarity;
pub mod cuida;
pub mod eos_icons;
pub mod fa7_brands;
pub mod fluent;
pub mod game_icons;
pub mod gg;
pub mod hugeicons;
pub mod icon_park_outline;
pub mod ion;
pub mod ix;
pub mod lets_icons;
pub mod line_md;
pub mod lucide;
pub mod material_symbols;
pub mod material_symbols_light;
pub mod mdi;
pub mod mingcute;
pub mod mynaui;
pub mod octicon;
pub mod proicons;
pub mod qlementine_icons;
pub mod radix_icons;
pub mod simple_icons;
pub mod solar;
pub mod streamline_ultimate;
pub mod tabler;
pub mod uil;
