/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-17T14:34:52.511534+00:00
/// Collection: radix-icons
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/radix-icons/>
///
/// ```yaml
/// name: Radix Icons
/// author:
///   name: WorkOS
///   url: https://github.com/radix-ui/icons
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/radix-ui/icons/blob/master/LICENSE
/// total: 332
/// category: UI Other / Mixed Grid
/// palette: false
/// height: 15
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const OpenInNewWindow: IconData = IconData {
    name: "radix-icons:open-in-new-window",
    body: r#"<path fill="currentColor" d="M8.5 6q.049 0 .098.009q.076.017.142.054q.061.034.114.083q.05.052.082.113A.5.5 0 0 1 9 6.5v3a.5.5 0 0 1-1 0V7.707l-5.146 5.147a.5.5 0 1 1-.708-.707L7.293 7H5.5a.5.5 0 0 1 0-1zM12 2a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H8.5a.5.5 0 0 1 0-1H12V3H3v3.5a.5.5 0 0 1-1 0V3a1 1 0 0 1 1-1z"/>"#,
    view_box: "0 0 15 15",
    width: "15",
    height: "15",
};
