/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-26T10:27:29.544833+00:00
/// Collection: simple-icons
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/simple-icons/>
///
/// ```yaml
/// name: Simple Icons
/// author:
///   name: Simple Icons Collaborators
///   url: https://github.com/simple-icons/simple-icons
/// license:
///   title: CC0 1.0
///   spdx: CC0-1.0
///   url: https://github.com/simple-icons/simple-icons/blob/develop/LICENSE.md
/// total: 3446
/// category: Logos
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Googlegemini: IconData = IconData {
    name: "simple-icons:googlegemini",
    body: r#"<path fill="currentColor" d="M11.04 19.32Q12 21.51 12 24q0-2.49.93-4.68q.96-2.19 2.58-3.81t3.81-2.55Q21.51 12 24 12q-2.49 0-4.68-.93a12.3 12.3 0 0 1-3.81-2.58a12.3 12.3 0 0 1-2.58-3.81Q12 2.49 12 0q0 2.49-.96 4.68q-.93 2.19-2.55 3.81a12.3 12.3 0 0 1-3.81 2.58Q2.49 12 0 12q2.49 0 4.68.96q2.19.93 3.81 2.55t2.55 3.81"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
