/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-26T10:33:17.129726+00:00
/// Collection: streamline-ultimate
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/streamline-ultimate/>
///
/// ```yaml
/// name: Ultimate free icons
/// author:
///   name: Streamline
///   url: https://github.com/webalys-hq/streamline-vectors
/// license:
///   title: CC BY 4.0
///   spdx: CC-BY-4.0
///   url: https://creativecommons.org/licenses/by/4.0/
/// total: 1999
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Hierarchy5Organize: IconData = IconData {
    name: "streamline-ultimate:hierarchy-5-organize",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M18.25.75H5.75A.75.75 0 0 0 5 1.5v5c0 .414.336.75.75.75h12.5A.75.75 0 0 0 19 6.5v-5a.75.75 0 0 0-.75-.75M12 7.25v11.5m-9 0v-4a1.5 1.5 0 0 1 1.5-1.5h15a1.5 1.5 0 0 1 1.5 1.5v4m-18 4.5a2.25 2.25 0 1 0 0-4.5a2.25 2.25 0 0 0 0 4.5m9 0a2.25 2.25 0 1 0 0-4.5a2.25 2.25 0 0 0 0 4.5m9 0a2.25 2.25 0 1 0 0-4.5a2.25 2.25 0 0 0 0 4.5"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const MoveToBottom: IconData = IconData {
    name: "streamline-ultimate:move-to-bottom",
    body: r#"<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"><path d="M.75.748h6v6h-6zm0 9.75v-.75h1.5m0 4.5H.75v-.75m6 0v.75h-1.5m-3 9H.75v-1.5m6 0v1.5h-1.5m0-13.5h1.5v.75m-6 8.25v-1.5h1.5m3 0h1.5v1.5m8.25-3l-3.75 3.75l3.75 3.75"/><path d="M11.25 19.5h4.5a7.5 7.5 0 0 0 0-15h-4.5"/></g>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
