/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-25T07:22:14.440346+00:00
/// Collection: tabler
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/tabler/>
///
/// ```yaml
/// name: Tabler Icons
/// author:
///   name: Paweł Kuna
///   url: https://github.com/tabler/tabler-icons
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/tabler/tabler-icons/blob/master/LICENSE
/// total: 6146
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const FolderShare: IconData = IconData {
    name: "tabler:folder-share",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 19H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h4l3 3h7a2 2 0 0 1 2 2v4m-5 9l5-5m0 4.5V17h-4.5"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};

#[allow(non_upper_case_globals)]
pub const Heart: IconData = IconData {
    name: "tabler:heart",
    body: r#"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.5 12.572L12 20l-7.5-7.428A5 5 0 1 1 12 6.006a5 5 0 1 1 7.5 6.572"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
