/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-03T10:18:13.691516+00:00
/// Collection: uil
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/uil/>
///
/// ```yaml
/// name: Unicons
/// author:
///   name: Iconscout
///   url: https://github.com/Iconscout/unicons
/// license:
///   title: Apache 2.0
///   spdx: Apache-2.0
///   url: https://github.com/Iconscout/unicons/blob/master/LICENSE
/// total: 1215
/// category: UI 24px
/// palette: false
/// height: 24
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const Desktop: IconData = IconData {
    name: "uil:desktop",
    body: r#"<path fill="currentColor" d="M19 3H5a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h6v2H7a1 1 0 0 0 0 2h10a1 1 0 0 0 0-2h-4v-2h6a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3m1 11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1Z"/>"#,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
